name: Setup Pesde
description: Installs Pesde CLI and authenticates with the registry

inputs:
  lune-version:
    description: "Version of Lune to install"
    required: false
  pesde-version:
    description: "Version of Pesde to install"
    required: false
  token:
    description: "Token for publishing to the Pesde registry"
    required: false

runs:
  using: composite
  steps:
    - name: Download Pesde and Lune
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        case ${{ runner.arch }} in
          "X86" | "X64") fileArch="x86_64" ;;
          "ARM" | "ARM64") fileArch="aarch64" ;;
        esac

        case ${{ runner.os }} in
          Linux) pattern="*linux-$fileArch.zip" ;;
          macOS) pattern="*macos-$fileArch.zip" ;;
          Windows) pattern="*windows-$fileArch.zip" ;;
        esac

        gh release download ${{ inputs.pesde-version }} --repo pesde-pkg/pesde --pattern $pattern
        gh release download ${{ inputs.lune-version }} --repo lune-org/lune --pattern $pattern

    - name: Install Pesde and Lune
      shell: bash
      run: |
        unzip pesde*.zip lune*.zip
        mv lune* lune
        chmod +x pesde lune
        ./pesde self-install

    - name: Remove artifacts
      shell: bash
      run: |
        rm pesde*.zip lune*.zip
        if ${{ runner.os == 'Windows' }}; then
          rm pesde.exe
        else
          rm pesde
        fi

    - name: Set Windows env variable
      if: runner.os == 'Windows'
      shell: bash
      run: |
        echo "$HOME/.pesde/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "lune" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Set env variable
      if: runner.os != 'Windows'
      shell: bash
      run: |
        echo "$HOME/.pesde/bin" >> $GITHUB_PATH
        echo "lune" >> $GITHUB_PATH

    - name: Authenticate into Pesde registry
      if: inputs.token != ''
      shell: bash
      run: pesde auth login --token "${{ inputs.token }}"

branding:
  icon: box
  color: blue
