name: Pesde setup test
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pesde
        uses: ./

      - name: Install dependencies
        run: pesde -v
