name: Pesde setup test
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pesde
        uses: ./
        with:
            pesde-version: 'v0.5.0-rc.13'
            lune-version: 'v0.8.9'

      - name: Test Pesde commands
        run: |
            pesde -v
            pesde add pesde/hello
            pesde install
      - name: Test Lune commands
        run: |
            lune -V
            lune run .lune/test.luau

