name: Pesde setup test
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pesde
        uses: ./

      - name: Verify Pesde version
        run: pesde -v
